jwt:
  secret: usersecret

#springdoc:
#  enable-native-support: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/appointify}
    username: ${DATASOURCE_USERNAME:default}
    password: ${DATASOURCE_PASSWORD:default}
    driver-class-name: org.postgresql.Driver